### ISSUE TITLE
HM3D semantic annotations?

### ISSUE THREAD

**Issue by giuliano-97** [matterport/habitat-matterport-3dresearch#14]
Where are the annotations mentioned here: https://aihabitat.org/datasets/hm3d-semantics/ ?

There are some links to annotation files in the README of some branches, but they are broken.

**Comment by IFICL** [comment]
Hi, Do you get any chance to make it work? I download the annotation from a certain branch and load semantic.glb. However, I was told that there is no semantic annotation.

**Comment by giuliano-97** [comment]
> Hi, Do you get any chance to make it work? I download the annotation from a certain branch and load semantic.glb. However, I was told that there is no semantic annotation.

I got it to work a couple of months ago. After getting approval (which took quite some time, you may want to make sure that actually got it first), I used the download utilities of the habitat_sim project and passed the asset id to download these semantics annots.
