### ISSUE TITLE
Unable to obtain Habitat - Matterport 3D Research Dataset

### ISSUE THREAD

**Issue by ningyuanz** [matterport/habitat-matterport-3dresearch#15]
Hello, I submitted application to Matterport three weeks ago but still cannot get an approval. As a result we are getting stuck due to lack of training data. Do you have any information why the process is getting so slow? Or is there a way to work around?

**Comment by aclegg3** [comment]
@ningyuanz I hope you are no longer waiting for access. This issue is stale, so hopefully not. Please re-open if so and we can look into it.
