### ISSUE TITLE
Problems about connection with Matterport3D

### ISSUE THREAD

**Issue by fangchuan** [matterport/habitat-matterport-3dresearch#18]
Hi all, I am really appreciate your excellent work, but I'm curious about is there any connection with the previous work Matterport3D dataset? To the beast of my knowledge, the only way I can have access to Habitat M3D is on the [github](https://github.com/matterport/habitat-matterport-3dresearch).  It seems that there is only a textured mesh in each scene of Habitat M3D, I cannot find more useful data such as camera poses, panorama, semantic segmentation and depth images, which is available in Matterport3D. You know, only textured mesh will limit the applications in the research community, we prefer more informative data in Habitat M3D.

I am looking forward to your reply, thanks in advance! 
@haeric @aclegg3 @apatel-matterport    @srama2512

**Comment by dhruvbatra** [comment]
There are no plans right now to release the raw RGBD panoramas. You can of course create a dataset of rendered RGBD images with associated poses using Habitat-Sim. Semantic annotations are available (for a growing subset) as part of HM3D-Semantic:

https://aihabitat.org/datasets/hm3d-semantics/

**Comment by fangchuan** [comment]
> There are no plans right now to release the raw RGBD panoramas. You can of course create a dataset of rendered RGBD images with associated poses using Habitat-Sim. Semantic annotations are available (for a growing subset) as part of HM3D-Semantic:
> 
> https://aihabitat.org/datasets/hm3d-semantics/

Thanks for your reply! 
Another question I want to figure out is that what's the essential difference between HM3D v0.1 & v0.2 ?
It is clear to see we have textured mesh model for each scene in v0.1, these obj+mtl files were replaced by a single glb file in v0.2, are there differences between two scenes in the two version?

**Comment by dhruvbatra** [comment]
The primary change in the increase in semantic annotations: https://aihabitat.org/datasets/hm3d-semantics/

There are some minor changes in the the geometry of the scenes (we manually cleaned up some reconstruction artifacts), but that is for a small number of scenes.
