### ISSUE TITLE
Working with Habitat Simulator

### ISSUE THREAD

**Issue by dasupradyumna** [matterport/habitat-matterport-3dresearch#19]
Hello guys, many thanks for the dataset!

I have used **Matterport3D** dataset before this. But for HM3D dataset, on loading the GLB files provided for various scenes in the tarballs, I noticed that I am not able to save the ground truth poses of the agent during navigation. I also notice the absence of navigation support i.e, no physical boundaries to constrain the agent while moving. This makes moving the agent up or down staircases a bit unnatural and odd compared to Matterport3D. I see a `.navmesh` file and tried to load it along with the GLB using the `habitat-viewer` tool but it does not work for some reason. Why has it been provided?

Am I missing something? How was this dataset intended to be used with Habitat simulator?
I would love it if someone can help!
Regards.

**Comment by aclegg3** [comment]
Hello @dasupradyumna,

Thanks for reaching out. Please take a look at [Habitat-sim dataset documentation for HM3D](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d). There are example snippets and use instructions for testing the assets in-engine. 

My guess is that you need to specify the dataset path in the simulator config. If you don't find your solution in the docs, please feel free to re-open this issue or open a new one if the issues change.
