### ISSUE TITLE
Format mismatch in hm3d-example-semantic-configs-v0.2

### ISSUE THREAD

**Issue by havocado** [matterport/habitat-matterport-3dresearch#22]
Hello, the filename format inside hm3d-example-semantic-configs-v0.2 doesn't match the filename format in hm3d-example-semantic-annots-v0.2.

**Dataset: hm3d-example-semantic-annots-v0.2**
Filenames:
  - GLAQ4DNUx5U.semantic.txt
  - GLAQ4DNUx5U.semantic.glb

**Dataset: hm3d-example-semantic-configs-v0.2** 
Filename: hm3d_annotated_example_basis
Line 25-26
```json
"semantic_descriptor_filename": "%%CONFIG_NAME_AS_ASSET_FILENAME%%_semantic.txt",
"semantic_asset": "%%CONFIG_NAME_AS_ASSET_FILENAME%%_semantic.ply",
```
Can be changed into
```json
"semantic_descriptor_filename": "%%CONFIG_NAME_AS_ASSET_FILENAME%%.semantic.txt",
"semantic_asset": "%%CONFIG_NAME_AS_ASSET_FILENAME%%.semantic.glb",
```

Thank you!

**Comment by aclegg3** [comment]
Thanks @havocado, good catch. :+1:

**Comment by srama2512** [comment]
Thanks for the catch, @havocado. The updated semantic configs have been uploaded.
