### ISSUE TITLE
Data download failed, no datasource named hm3d_minival-v0.2

### ISSUE THREAD

**Issue by SongDoHou** [matterport/habitat-matterport-3dresearch#34]
Hi, thank you for sharing the dataset.

However, I'm facing the issue with download the data from the following command:
python -m habitat_sim.utils.datasets_download --username xxx --password xxx --uids hm3d_minival-v0.2
and following error:
 Data download failed, no datasource named hm3d_minival-v0.2

When I remove "-v0.2" (--uids hm3d_minival), it works.
Is there any problem with my command for downloading?

**Comment by 2003jiahang** [comment]
Hello!
I met the same issue!!! Can you tell me how you resolve this issue?
It is really important to me.

**Comment by sunq020718-dot** [comment]
if you guys still interested, it is actually has something to do with "habitat_sim.utils.datasets_download" this Script. if the version of habitat_sim is too old,it does not contain the hm3d_minival-v0.2 in its datagroup. so you need either to update your habitat_sim or you can just use the datasets_download script from https://github.com/facebookresearch/habitat-sim/blob/main/src_python/habitat_sim/utils/datasets_download.py. These will solve~
