### ISSUE TITLE
Where can I find the semantic annotations?

### ISSUE THREAD

**Issue by Ending2015a** [matterport/habitat-matterport-3dresearch#7]
Hello, 
I'm trying to use semantic sensor in [habitat-lab](https://github.com/facebookresearch/habitat-lab) to get the ground truth semantic image. I've downloaded this dataset: `hm3d-minival-habitat.tar`. And I think the scene is correctly loaded, but the semantic image is black (zeros), and it shows 'The active scene does not contain semantic annotations.'
```
[12:10:20:220323]:[Sim] Simulator.cpp(457)::instanceStageForSceneAttributes :
---
The active scene does not contain semantic annotations.
---
```
Does that mean that I need to download semantic annotations from somewhere else?

**Comment by erikwijmans** [comment]
HM3D currently doesn't have semantic annotations. This is something we are working on, but nothing to announce currently. Stay tuned!

**Comment by KarelZhang** [comment]
> HM3D currently doesn't have semantic annotations. This is something we are working on, but nothing to announce currently. Stay tuned!

Hi, I got the same problem, but I have downloaded the semantic annotations now, and put the *semantic.glb and the *basis.glb in the same dir.

Is there anything wrong?
